services:
  wireguard:
    image: wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - IP_SERVER=10.0.0.1/24
      - NUMBER_CLIENT=5
      - DNS=8.8.8.8